deploy_static:
  stage: deploy
  image: google/cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file $serviceaccounttoken
    - gcloud functions deploy PythonCanyonScraper --region=us-central1 --runtime=python37 --trigger-topic=CanyonScraperInitiation --service-account=canyon-scraper-service-acc@canyonscraper.iam.gserviceaccount.com --set-env-vars=twilio_auth_token=$twilio_auth_token > gcp_output_from_function_deploy.txt
    - cat gcp_output_from_function_deploy.txt