deploy_static:
  stage: deploy
  image: google/cloud-sdk
  script:
    - gcloud auth activate-service-account --key-file $serviceaccounttoken
    - gcloud functions deploy PythonCanyonScraper --region=us-central1 --project=canyonscraper --runtime=python37 --trigger-topic=CanyonScraperInitiation --service-account=$bensServiceAccount --set-env-vars=twilio_auth_token=$twilio_auth_token;TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID > gcp_output_from_function_deploy.txt
    - cat gcp_output_from_function_deploy.txt